[package]
name = "metricator"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Metrics"
repository = "https://github.com/piot/metricator"

[dependencies]
num-traits = "^0.2"
monotonic-time-rs = "^0.0.3"

[dev-dependencies]
test-log = "^0.2.16"
